### ISSUE TITLE
Mudar titulo da janela de acordo com a opção do menu

### ISSUE THREAD

**Issue by z4nnk** [d0uglas77p/ControleEnergia#11]
- **Seu problema ou necessidade:** <br>
n/a

- **Descrição da Nova Funcionalidade:** <br>
Quando clicar em uma opção de menu no aplicativo, mudar o titulo da jenela, ex:
clicar na opção de inicio, mudar o titulo da janela para inicio.
clicar na opção de companhias, mudar o titulo da janela para companhias.

- **Benefícios para o Usuário:** <br>
usuário irá se encontrar melhor na navegação do aplicativo.

- **Melhoria de Desempenho do Aplicativo:** <br>
n/a.

- **Requisitos Técnicos (se aplicável):** <br>
n/a

- **Capturas de Tela (se aplicável):** <br>
n/a

- **Notas Adicionais:** <br>
n/a

**Comment by d0uglas77p** [comment]
✌

**Comment by d0uglas77p** [comment]
https://github.com/d0uglas77p/ControleEnergia/pull/13#issue-2272412155

**Comment by d0uglas77p** [comment]
https://github.com/d0uglas77p/ControleEnergia/pull/13#issue-2272412155
